### ISSUE TITLE
Spotting height

### ISSUE THREAD

**Issue by sanekun** [Lelp27/automated-protocol-ot2#1]
dest.bottom(z=4)
touch tip 필요 없음

{
  "Plates": {
    "DNA_plate_0_name": {
      "data": {
        "A1": "pACBB_4-5",
        "C1": "pET-28a(+)",
        "A2": "pACBB_4-5_T7pad FWD",
        "B2": "pACBB_T7-F1",
        "C2": "pET-28a(+) FWD",
        "A3": "pACBB_vec-R2",
        "B3": "pACBB_4-5_T7pad REV",
        "C3": "pET-28a(+) REV"
      },
      "labware": "biorad_96_wellplate_200ul_pcr",
      "type": "DNA"
    },
    "Reaction_plate_0_name": {
      "data": {
        "F1": "G1",
        "G1": "G2",
        "H1": "G3",
        "F4": "Phusion",
        "G4": "HiFi"
      },
      "labware": "biorad_96_wellplate_200ul_pcr",
      "type": "Reaction"
    },
    "TF_plate_0_name": {
      "data": {
        "A1": "Phusion",
        "B1": "Phusion",
        "E1": "HiFi",
        "F1": "HiFi",
        "A2": "Phusion",
        "B2": "Phusion",
        "E2": "HiFi",
        "F2": "HiFi",
        "A3": "Phusion",
        "B3": "Phusion",
        "E3": "HiFi",
        "F3": "HiFi",
        "A4": "Phusion",
        "B4": "Phusion",
        "E4": "HiFi",
        "F4": "HiFi",
        "A5": "Phusion",
        "B5": "Phusion",
        "E5": "HiFi",
        "F5": "HiFi",
        "A6": "Phusion",
        "B6": "Phusion",
        "E6": "HiFi",
        "F6": "HiFi"
      },
      "labware": "biorad_96_wellplate_200ul_pcr",
      "type": "TF"
    }
  },
  "Reactions": {
    "PCR_plate_0_name": {
      "data": {
        "Name": {
          "0": "G1",
          "1": "G2",
          "2": "G3"
        },
        "DNA1": {
          "0": "pACBB_4-5",
          "1": "pACBB_4-5",
          "2": "pET-28a(+)"
        },
        "DNA2": {
          "0": "pACBB_4-5_T7pad FWD",
          "1": "pACBB_T7-F1",
          "2": "pET-28a(+) FWD"
        },
        "DNA3": {
          "0": "pACBB_vec-R2",
          "1": "pACBB_4-5_T7pad REV",
          "2": "pET-28a(+) REV"
        },
        "Enzyme1": {
          "0": "PCRMix",
          "1": "PCRMix",
          "2": "PCRMix"
        },
        "DW": {
          "0": "DW",
          "1": "DW",
          "2": "DW"
        }
      },
      "type": "PCR"
    },
    "Assembly_plate_0_name": {
      "data": {
        "Name": {
          "0": "Phusion",
          "1": "HiFi"
        },
        "DNA1": {
          "0": "G1",
          "1": "G1"
        },
        "DNA2": {
          "0": "G2",
          "1": "G2"
        },
        "DNA3": {
          "0": "G3",
          "1": "G3"
        },
        "Enzyme1": {
          "0": "HotPhusion",
          "1": "NEBHiFi"
        },
        "DW": {
          "0": "DW",
          "1": "DW"
        }
      },
      "type": "Assembly"
    }
  },
  "Reaction_volume": {
    "PCR": {
      "DNA1": "0.5",
      "DNA2": "0.4",
      "DNA3": "0.4",
      "Enzyme1": "12.5",
      "DW": "10"
    },
    "Assembly": {
      "DNA1": "1",
      "DNA2": "1",
      "DNA3": "1",
      "Enzyme1": "10",
      "DW": "8"
    }
  },
  "Parameters": {
    "Number of Plate": 3,
    "Plate_type": [
      "DNA",
      "Reaction",
      "TF"
    ],
    "Reaction_type": [
      "PCR",
      "Assembly"
    ],
    "Enzyme_position": {
      "HotPhusion": "A1",
      "NEBHiFi": "A2",
      "PCRMix": "A3",
      "DW": "A4",
      "CPcell": "B1",
      "LB": "B2"
    },
    "Deck_position": {
      "Enzyme_tube": 1,
      "p20_tip": 2,
      "p300_tip": 3,
      "DNA_plate_0_name": 4,
      "Reaction_plate_0_name": 7,
      "TF_plate_0_name": 5
    },
    "number_of_tips": null
  }
}

**Comment by sanekun** [comment]
pipette.mix 시 picked_tip이 없어도 작동하는 지 확인
-> 작동 안함

**Comment by sanekun** [comment]
# 231229 실제 테스트
- [x] DW 분주 시 Mix & Touch tip & blow_out 삭제
- [x] Assembly 단계 PCR product를 딸 때 속도줄임, Blow_out 필요 (Enzyme 취급)
- [x] CP cell 분주 전 매번 mix 하던거 한번으로 변경
- [x] CP cell 분주 후  mix_after
- [x] LB, CP cell 따는 위치 살짝 올리기(z=3)
- [x] thermocycler deactivate -> Recovery transfer -> temperature(37) (온도가 변하는 시간 동안 동작이 정지됨)
- [x] Spotting 에 touch tip 삭제

**Comment by Lelp27** [comment]
> e.mix 시 picked_tip이 없어

작동 안함

**Comment by sanekun** [comment]
# DNA dispense 시간 줄이기

DNA 다넣고 Mix 시간 줄이기
PCR blow_out 빼기
컴셀 넣고 믹스하는 시간 줄이기

**Comment by sanekun** [comment]
Recovery 할 때 Lid deactivation

**Comment by sanekun** [comment]
Spotting 직전 Cell mix하기
