### ISSUE TITLE
Update v0.1

### ISSUE THREAD

**Issue by sanekun** [Lelp27/automated-protocol-ot2#4]
- [x] "nan" object  
Well plate 에서 well이 비워져있으면 "nan" 입력됨

### DNA dispense 시간 줄이기
- [x] DNA 다 넣고 Mix 시간 줄이기
- [x] PCR blow_out 빼기
- [x] 컴셀 넣고 믹스하는 시간 줄이기

### Assembly
- [x] Master mix volume 5 ul로 줄이기

### 기타
- [x] Recovery에 Lid deactivation
- [x] Spotting 직전 Cell mix 하기
- [x] CP cell & DNA 섞고 시간 기다리기
- [x] 처음 DNA 바로 TF 할 수 있는지 확인
-> Reaction Plate에 있으면 가능 (Thermocycler 사용 여부 때문)

**Comment by sanekun** [comment]
- [x] CP cell 분주 touch tip 삭제
- [x] CP cell 분주 시 첫 샘플 mix_before
- [x] protocol.delay 사용
- [x] CP cell 분주 전 까지 reaction plate 차갑게 유지 (뚜껑 닫아서)
- [x] Drop 전에 blow_out 다 빼기 (속도 줄임)
- [ ] Enzyme 분주 후에는 Touch tip 삭제
- [x] Spotting 에서 Tip 잡고 mix 후 Distribution 으로 수정
- [x] metadata의 Protocol name에 날짜 삽입하기

### DNA 바로 TF

DNA를 바로 TF 하려면 DNA를 Reaction Plate로 옮겨야 함
-> 처음부터 Reaction Plate에 있으면 바로 가능

**Comment by Lelp27** [comment]
Spotting 에서 Mix before 하니까 끊을 때 마다 매번 Mix 함.
-> Tip 잡고 Mix 후 Distribution 하는 것으로 수정

**Comment by Lelp27** [comment]
metadata의 Protocol Name에 날짜 삽입하기

**Comment by sanekun** [comment]
PCR시 denaturation 온도 94도로 낮추기 (Thermocycler 과열)
